server:
  port: 8084

spring:
  application:
    name: payment-service

  data:
    mongodb:
      database: paymentdb
      host: localhost
      port: 27017

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
